### ISSUE TITLE
Error during the consuming flow in Nile

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/commons#132] opened 2019-05-16 12:29 UTC
# Prerequisites

## Expected Behavior

When I try to consume/download an asset on Nile network I can do it without any issue.

## Current Behavior

Currently when I'm trying to download one asset, the flow is stuck showing the message:
""Decrypting file URL, please sign...""

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Step to Reproduce the problem

Please provide detailed steps for reproducing the issue.

1. Go to Nile
2. Get some ETH using the Faucet
3. Go to https://commons.oceanprotocol.com/asset/did:op:be2ab056265d44a6b406785702a1f654984c174d949c451f99e41f8fbea57a71 
4. Click on Download
5. Confirm 2 times in Metamask

![image](https://user-images.githubusercontent.com/1726644/57853542-5001f600-77e6-11e9-9c90-0eed7bf5aaf6.png)

**Comment by kremalicious** [comment] 2019-05-16 12:30
duplicate of #86 & #131

**Closed by kremalicious** 2019-05-16 12:30 UTC
Labels: bug, priority:high

**Comment by Pedro-vk** [comment] 2019-05-16 13:01
![image](https://user-images.githubusercontent.com/1885747/57855644-6b233480-77eb-11e9-9079-4ac4ea841873.png)
Do you have tokens in the account?

**Comment by aaitor** [comment] 2019-05-16 14:00
why/how an asset in commons is not free?
